#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

server:
  port: 14000

spring:

  #redis配置
  redis:
    host: 59.110.137.100
    port: 6379

  application:
    name: gulimall-es-14000
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.137.100:8848 #配置Nacos地址
  thymeleaf:
    cache: false


